---
# tasks file for roles/proxy
- name: Pull the proxy image
  docker_image:
    name: bdaipa/dockercompose-httpd
    tag: latest
    source: pull

- name: Run the proxy container
  docker_container:
    name: my-httpd
    image: bdaipa/dockercompose-httpd:latest
    ports:
      - "80:80"
    networks:
      - name: "my-network"

  vars:
    ansible_python_interpreter: /usr/bin/python3
